# Generated by Django 2.1.5 on 2019-02-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messaggio',
            options={'verbose_name': 'Messaggio', 'verbose_name_plural': 'Messaggi'},
        ),
    ]
